name: 'Create Issue on Workflow Failure'
description: 'Creates a GitHub issue when a workflow fails to notify watchers'
inputs:
  github-token:
    description: 'GitHub token for creating issues'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create issue on failure
      if: github.event_name != 'workflow_dispatch'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const workflow_name = context.workflow;
          const run_url = `${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

          const title = `Workflow failed: ${workflow_name}`;
          const body = run_url;

          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['workflow-failure', 'automated']
          });
