apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: doca1-rdma-privileged-scc
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: rdma
    namespace: default
