---
# General configurations.
verbose_level: 0
dump_failed_tests: false
reports_dump_dir: "/tmp/reports"
dry_run: false
kubernetes_role_prefix: "node-role.kubernetes.io"
worker_label: "worker"
control_plane_label: "control-plane"
...
